name: "Star Travels"
mode: "dev"
version: "v1.1"
port: 9999
start_time: "2022-01-01 00:00:00"
machine_id: 1

auth:
  jwt_expire: 240 # token过期时间为 jwt_expire hour

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

# 主节点配置（复制写操作）
mysql_master:
  host: "42.192.19.149"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "web_app"
  max_open_conns: 200
  max_idle_conns: 50

# 从节点配置
mysql_slave:
  count: 2   # 从节点个数
  host:        # 可填多个从节点的host
    - "175.178.248.84"
    - "175.178.248.84"
  port:
    - 3306
    - 3306
  user:
    - "root"
    - "root"
  password:
    - "123456"
    - "123456"
  dbname:
    - "web_app"
    - "web_app"
  max_open_conns: 200 # 为了简便这个保持一直
  max_idle_conns: 50

redis:
  sentinels:
    - "121.36.165.46:8000" # 只需要配置sentinel即可，sentinel来发现master ip
    - "121.36.165.46:8001"
    - "121.36.165.46:8002"

  password: "123456"
  replicas: 20 # 虚拟节点数
  masters:
    master_name:
      - "redis-master"
      - "redis-master-2"
    passwords:
      - "123456"
      - "123456"
    counts: 2

paramPostList: # 关于models params.go 结构体ParamPostList的一些默认值
  page: 1
  size: 10